Window.prototype.getComputedStyle;
Object.indexOf;
Object.Fragment;
Object.findDOMNode;
Object.Children;
Object.Children.toArray;
Object.render;
Object.out;
Object.out.println;
Object.createElement;
Object.createElement.apply;
Object.unmountComponentAtNode;
Object.error;
Object.error.println;
Audio.prototype.play;
HTMLDocument.prototype.querySelector;
HTMLDocument.prototype.createElement;
HTMLDocument.prototype.createElementNS;
HTMLDocument.prototype.createTextNode;
HTMLDocument.prototype.getElementById;
var process;
process.hrtime;
var Highcharts;
Highcharts.Chart;
window.setInterval;
var setTimeout;
var void$;
document.body;
var Java;
Java.type;
