// Compiled by ClojureScript 1.10.520 {:static-fns true, :optimize-constants true}
goog.provide('pomodoro.style');
goog.require('cljs.core');
goog.require('cljs.core.constants');
goog.require('stylefy.core');
pomodoro.style.color_deepblue = "#003164";
pomodoro.style.white_color = new cljs.core.PersistentArrayMap(null, 1, [cljs.core.cst$kw$color,"white"], null);
pomodoro.style.main_color = new cljs.core.PersistentArrayMap(null, 1, [cljs.core.cst$kw$color,"#FF4384"], null);
pomodoro.style.basic_layout = new cljs.core.PersistentArrayMap(null, 5, [cljs.core.cst$kw$display,"block",cljs.core.cst$kw$width,"1280px",cljs.core.cst$kw$height,"800px",cljs.core.cst$kw$margin,"0 auto",cljs.core.cst$kw$position,"relative"], null);
pomodoro.style.pomodoro_main = cljs.core.merge.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([pomodoro.style.basic_layout,new cljs.core.PersistentArrayMap(null, 1, [cljs.core.cst$kw$background_DASH_color,"#FFEDF7"], null)], 0));
pomodoro.style.pomodoro_config = cljs.core.merge.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([pomodoro.style.basic_layout,new cljs.core.PersistentArrayMap(null, 2, [cljs.core.cst$kw$background_DASH_color,pomodoro.style.color_deepblue,cljs.core.cst$kw$display,"flex"], null)], 0));
pomodoro.style.main_sider = new cljs.core.PersistentArrayMap(null, 6, [cljs.core.cst$kw$width,"450px",cljs.core.cst$kw$height,"800px",cljs.core.cst$kw$background_DASH_color,"#003164",cljs.core.cst$kw$display,"block",cljs.core.cst$kw$position,"absolute",cljs.core.cst$kw$right,"0px"], null);
pomodoro.style.circle = new cljs.core.PersistentArrayMap(null, 8, [cljs.core.cst$kw$position,"absolute",cljs.core.cst$kw$display,"block",cljs.core.cst$kw$width,"510px",cljs.core.cst$kw$height,"510px",cljs.core.cst$kw$border_DASH_radius,"510px",cljs.core.cst$kw$background_DASH_color,"#777",cljs.core.cst$kw$transition,"background-color .3s",cljs.core.cst$kw$stylefy$core_SLASH_mode,new cljs.core.PersistentArrayMap(null, 1, [cljs.core.cst$kw$before,new cljs.core.PersistentArrayMap(null, 8, [cljs.core.cst$kw$content,"",cljs.core.cst$kw$display,"block",cljs.core.cst$kw$width,"540px",cljs.core.cst$kw$height,"540px",cljs.core.cst$kw$border,"5px solid #777",cljs.core.cst$kw$border_DASH_radius,"540px",cljs.core.cst$kw$box_DASH_sizing,"border-box",cljs.core.cst$kw$transition,"border .3s"], null)], null)], null);
pomodoro.style.main_input = new cljs.core.PersistentArrayMap(null, 6, [cljs.core.cst$kw$width,"445px",cljs.core.cst$kw$height,"56px",cljs.core.cst$kw$color,"block",cljs.core.cst$kw$font_DASH_size,"16px",cljs.core.cst$kw$padding_DASH_left,"14px",cljs.core.cst$kw$stylefy$core_SLASH_mode,new cljs.core.PersistentArrayMap(null, 1, ["::placeholder",new cljs.core.PersistentArrayMap(null, 3, [cljs.core.cst$kw$color,"#FF4384",cljs.core.cst$kw$font_DASH_weight,"bold",cljs.core.cst$kw$padding_DASH_left,"16px"], null)], null)], null);
pomodoro.style.inner_circle = cljs.core.PersistentHashMap.fromArrays([cljs.core.cst$kw$transition,cljs.core.cst$kw$top,cljs.core.cst$kw$margin_DASH_left,cljs.core.cst$kw$background_DASH_color,cljs.core.cst$kw$margin_DASH_top,cljs.core.cst$kw$width,cljs.core.cst$kw$cursor,cljs.core.cst$kw$display,cljs.core.cst$kw$position,cljs.core.cst$kw$border_DASH_radius,cljs.core.cst$kw$height,cljs.core.cst$kw$left,cljs.core.cst$kw$margin],["transform .5s,background-color .3s","50%","-45px","#fff","-45px","90px","pointer","block","absolute","90px","90px","50%","0 auto"]);
pomodoro.style.circle_icon = new cljs.core.PersistentArrayMap(null, 4, [cljs.core.cst$kw$font_DASH_size,"50px",cljs.core.cst$kw$position,"absolute",cljs.core.cst$kw$left,"22%",cljs.core.cst$kw$top,"22%"], null);
pomodoro.style.circle_icon_2 = new cljs.core.PersistentArrayMap(null, 2, [cljs.core.cst$kw$position,"relative",cljs.core.cst$kw$font_DASH_size,"45px"], null);
